platform :ios, '10.0'
target 'VoIPCourseWork' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VoIPCourseWork
  pod 'WebRTC', '~> 125.0.0'
  pod 'Starscream', '~> 4.0.0'
end
